title: David Li # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelors in Mechanical Engineering (Mechatronics)
  <br><br>
  Masters in Electrical Engineering (Control Systems)
  <br><br>
  <a href="https://www.linkedin.com/in/davecyli/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
